/**
 * Database types for Supabase
 * This file will be auto-generated by Supabase CLI once the schema is set up
 * Run: npx supabase gen types typescript --local > src/lib/supabase/database.types.ts
 */

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
	public: {
		Tables: {
			// User API keys (encrypted)
			api_keys: {
				Row: {
					id: string;
					user_id: string;
					provider: string;
					encrypted_key: string;
					created_at: string;
					updated_at: string;
				};
				Insert: {
					id?: string;
					user_id: string;
					provider: string;
					encrypted_key: string;
					created_at?: string;
					updated_at?: string;
				};
				Update: {
					id?: string;
					user_id?: string;
					provider?: string;
					encrypted_key?: string;
					created_at?: string;
					updated_at?: string;
				};
			};
			// Prompt maps (saved sessions)
			prompt_maps: {
				Row: {
					id: string;
					user_id: string;
					folder_id: string | null;
					name: string;
					prompt: string;
					created_at: string;
					updated_at: string;
				};
				Insert: {
					id?: string;
					user_id: string;
					folder_id?: string | null;
					name: string;
					prompt: string;
					created_at?: string;
					updated_at?: string;
				};
				Update: {
					id?: string;
					user_id?: string;
					folder_id?: string | null;
					name?: string;
					prompt?: string;
					created_at?: string;
					updated_at?: string;
				};
			};
			// Model responses within a prompt map
			model_responses: {
				Row: {
					id: string;
					prompt_map_id: string;
					provider: string;
					model: string;
					response: string;
					rating: number | null;
					notes: string | null;
					latency_ms: number | null;
					created_at: string;
				};
				Insert: {
					id?: string;
					prompt_map_id: string;
					provider: string;
					model: string;
					response: string;
					rating?: number | null;
					notes?: string | null;
					latency_ms?: number | null;
					created_at?: string;
				};
				Update: {
					id?: string;
					prompt_map_id?: string;
					provider?: string;
					model?: string;
					response?: string;
					rating?: number | null;
					notes?: string | null;
					latency_ms?: number | null;
					created_at?: string;
				};
			};
			// Folders for organizing prompt maps
			folders: {
				Row: {
					id: string;
					user_id: string;
					parent_id: string | null;
					name: string;
					created_at: string;
				};
				Insert: {
					id?: string;
					user_id: string;
					parent_id?: string | null;
					name: string;
					created_at?: string;
				};
				Update: {
					id?: string;
					user_id?: string;
					parent_id?: string | null;
					name?: string;
					created_at?: string;
				};
			};
		};
		Views: {};
		Functions: {};
		Enums: {};
	};
}
